### ISSUE TITLE
Disallowed origin error message

### ISSUE THREAD

**Issue by mlereste** [bambora/na-customcheckout#67]
Hello,

FYI, when testing our integration, we are getting the following error in the console:

`CheckoutFields: remote received message from disallowed origin: http://XXX, expected: undefined`

The error comes from the file `https://libs.na.bambora.com/checkoutfields/2.0.0/checkoutfieldsremote.js` at line 1121

**Comment by mlereste** [comment]
In the above comment, "http://XXX" is a host like locahlhost or even dev.abc.com

**Comment by e-wipond** [comment]
Thanks. Is this breaking your integration? Or just polluting the console.

**Comment by mlereste** [comment]
@e-wipond We think it might be breaking our integration under Firefox, but I'm still debugging as I wrote to confirm

**Comment by e-wipond** [comment]
We were logging errors regarding postMessages from unexpected origins a little enthusiastically. This should no longer be an issue on the dev branch (now deployed at `https://s3.ca-central-1.amazonaws.com/na-customcheckout.dev/2.0.0/customcheckout.js`).

**Comment by e-wipond** [comment]
Closing as this should be fixed in production now.
