### ISSUE TITLE
iFrame height is 0px under Firefox

### ISSUE THREAD

**Issue by mlereste** [bambora/na-customcheckout#69]
Hello,

We face an issue under Firefox (53.0.3). The iFrame fields are loaded, but are not visible because they have a CSS height of 0px.

Here is a screencapture of Firefox HTML inspector

![firefox-bug](https://user-images.githubusercontent.com/10930638/27434639-6cb29ff2-5727-11e7-8cfb-9978d2efc382.png)

**Comment by mlereste** [comment]
A bit of update:

The function `View.prototype._updateIFrame` in file `checkoutfields.js` on line 618 receive the following data input:

```
Object { type: "cvv", inputHeight: "0px" }
Object { type: "expiry", inputHeight: "0px" }
Object { type: "card-number", inputHeight: "0px" }
```

**Comment by mlereste** [comment]
By the way, setting the initial css height of the iFrame fields to 0px is a bit agressive in my opinion. (see line 646 of file `checkoutfields.js`).

I understand that the height of the iFrame will be modify base on the input real height (user can provide custom CSS so the height might vary), but setting it to 0 straight from the beginning is a weird choice. Am I missing anything that might explain this choice?

**Comment by mlereste** [comment]
@e-wipond Any feedback on this for s? This is a blocking issue for us to release in the upcomming days

**Comment by mlereste** [comment]
For now we managed to fix this by doing some CSS, but it will need to be fix in the lib for sure.

Fix:
```css
/* Workarround for Firefox */
.cc-field iframe {
    height: 18px!important;
}

```

**Comment by e-wipond** [comment]
Hi. I think the issue is related to using `document.documentElement.scrollHeight` to set the height of the iframes. Still digging into it to find a fix.

There should be various bug fixes being merged on the dev branch today.

**Comment by mlereste** [comment]
@e-wipond Ok cool thanks. We came to the same conclusion on our side that `document.documentElement.scrollHeight` might be the problem.

You seem to set the height to 100% on the input, which can be problematic when calling `document.documentElement.scrollHeight` under Firefox (this is an hypothesis, need to be confirmed on your side).

**Comment by e-wipond** [comment]
Thanks for digging into it. I'm having trouble replicating the issue, firefox seems to be working okay on a few different machines / versions for me.  Do you experience the same issue at this link: https://codepen.io/ethanvv/pen/rwwNbV

**Comment by mlereste** [comment]
No the issue is not replicated. On the link you provided it seems to work under Firefox.

**Comment by e-wipond** [comment]
Okay, thank you. Looks like it will work on codpen in firefox, but not in other scenarios.

**Comment by mlereste** [comment]
It playing arround with your codepen. If we can't replicate it, we might consider share with you our implementation so you can take a look and spot if there are differences/errors

**Comment by e-wipond** [comment]
I see the same issue in firefox when not going through codepen. I'll work on a fix.

**Comment by mlereste** [comment]
:+1:  Thanks men, good support. Keep going!

**Comment by e-wipond** [comment]
Hey, looking at this again, I can't actually replicate the bug in Firefox. Can you try out our test page and api demo and confirm if those fields are displaying correctly for you? 

[https://demo.na.bambora.com/](https://demo.na.bambora.com/)
[https://s3.ca-central-1.amazonaws.com/na-checkoutfields.master/2.0.0/demo.html?source=production](https://s3.ca-central-1.amazonaws.com/na-checkoutfields.master/2.0.0/demo.html?source=production)

**Comment by mlereste** [comment]
Yes seems good on my end
