### ISSUE TITLE
CVD Not Provided

### ISSUE THREAD

**Issue by fboutin-pmc** [bambora/na-customcheckout#70]
We are getting a `CVD Not Provided` in `CVD result` when pre-authorizing from a Payment Profile created with a Token provided by the checkoutfields.

We properly mount the CVV field but it seems that somehow the data don't make it through.

Any help?

Thank you!

**Comment by e-wipond** [comment]
Hi, does this happen consistently?

**Comment by fboutin-pmc** [comment]
Hum... I just tried by manually calling POST tokens, POST profiles and POST payments with the help of bambora postman setup and I reproduce the same issue - i.e. outside checkoutfields.

I guess the problem resides somewhere else then.

**Comment by fboutin-pmc** [comment]
I dropped an email behind the scenes so we can figure what's going on here.

**Comment by fboutin-pmc** [comment]
Here is the answer we finally got,

> This response is due to the fact that the CVV is not stored on the Payment Profile and so not passed to the processor with the transaction request.

> The cvv is present in the single use token that is returned from Custom Checkout.

I suppose we can close the issue.
